<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

/**
 * Layered navigation js initialize template
 *
 * @var $block \Magento\Framework\View\Element\Template
 */

/** @var \Buhmann\Catalog\ViewModel\LayeredNavigation $viewModel */
$viewModel = $block->getData('config');
$isInfiniteScroll = $viewModel && $viewModel->isInfiniteScroll();
$isSaveScrollHistory = $viewModel && $viewModel->isSaveScrollHistory();
?>
<script type="text/x-magento-init">
{
    "*": {
        "infiniteScroll": {
            "productWrapper": ".products.list.items",
            "productItem": ".product-item",
            "nextBtn": ".pages-item-next a",
            "pagination": ".pages",
            "loaderImage": "<?php echo $block->getViewFileUrl('images/loader-2.gif'); ?>",
            "infiniteScroll": <?= $isInfiniteScroll ? 'true' : 'false' ?>,
            "saveHistory": <?= $isSaveScrollHistory ? 'true' : 'false' ?>
        }
    }
}
</script>
