<?php
/**
 * Copyright © Buhmann. All rights reserved.
 *
 * Layered navigation js initialize template
 *
 * @var $block \Magento\Framework\View\Element\Template
 * @var $viewModel \Buhmann\Catalog\Api\ViewModel\LayeredNavigationInterface
 */
$viewModel = $block->getData('config');
?>
<?php if ($viewModel->isAdvancedCatalogEnabled()): ?>
    <div style="display:none;" data-bind="scope: 'catalogViewBinder'"></div>

    <script type="text/x-magento-init">
        {
            "[data-bind=\"scope: 'catalogViewBinder'\"]": {
                "Magento_Ui/js/core/app": {
                    "components": {
                        "catalogViewBinder": {
                            "component": "Buhmann_Catalog/js/catalog-view-binder"
                        }
                    }
                }
            }
        }
    </script>

    <?php if ($viewModel->isInfiniteScroll()): ?>
    <script type="text/x-magento-init">
    {
        "*": {
            "infiniteScroll": {
                "productWrapper": ".products.list.items",
                "productItem": ".product-item",
                "nextBtn": ".pages-item-next a",
                "pagination": ".pages",
                "loaderImage": "<?php echo $block->getViewFileUrl('images/loader-2.gif'); ?>",
                "savePageHistory": <?= $viewModel && $viewModel->isSaveScrollHistory() ? 'true' : 'false' ?>
            }
        }
    }
    </script>
    <?php endif; ?>
<?php endif; ?>
