<?php
/**
 * Copyright © Buhmann. All rights reserved.
 */
declare(strict_types=1);

namespace Buhmann\Catalog\Plugin\Model\Layer\Filter;

use Buhmann\Catalog\Api\ViewModel\LayeredNavigationInterface;
use Magento\Catalog\Model\Layer\Filter\AbstractFilter;
use Magento\Catalog\Model\Layer\Filter\Item as Subject;
use Magento\Framework\Exception\LocalizedException;
use Magento\Framework\UrlInterface;
use Magento\Theme\Block\Html\Pager;

class Item
{
    /**
     * @var LayeredNavigationInterface
     */
    private LayeredNavigationInterface $viewModel;

    /**
     * @var UrlInterface
     */
    private UrlInterface $url;

    /**
     * @var Pager
     */
    private Pager $pager;

    /**
     * Constructor
     *
     * @param LayeredNavigationInterface $viewModel Layered navigation view model
     * @param UrlInterface $url URL builder
     * @param Pager $pager Pager block
     */
    public function __construct(
        LayeredNavigationInterface $viewModel,
        UrlInterface $url,
        Pager $pager
    ) {
        $this->viewModel = $viewModel;
        $this->url = $url;
        $this->pager = $pager;
    }

    /**
     * Modify filter item URL to support multi-select functionality
     *
     * @param Subject $subject The filter item instance
     * @param string $result The original URL generated by the method
     * @return string Modified URL with multi-select parameters
     * @throws LocalizedException
     */
    public function afterGetUrl(Subject $subject, string $result): string
    {
        if (!$this->viewModel->isMultiSelectEnabled()) {
            return $result;
        }

        $filter = $subject->getFilter();
        $selectedValues = $this->getSelectedValues($filter);
        $itemValue = $subject->getValue();

        $isSelected = in_array($itemValue, $selectedValues, true);

        $query = [];

        if ($isSelected) {
            $remainingValues = array_values(array_diff($selectedValues, [$itemValue]));
            if (!empty($remainingValues)) {
                $query[$filter->getRequestVar()] = $remainingValues;
            } else {
                // Explicitly remove filter parameter to deselect the item
                $query[$filter->getRequestVar()] = null;
            }
        } else {
            $query[$filter->getRequestVar()] = array_merge($selectedValues, [$itemValue]);
        }

        $query[$this->pager->getPageVarName()] = null;

        return $this->url->getUrl('*/*/*', [
            '_current' => true,
            '_use_rewrite' => true,
            '_query' => $query,
            '_escape' => false
        ]);
    }

    /**
     * Get currently selected values for a specific filter
     *
     * @param AbstractFilter $filter The filter instance
     * @return array Array of selected filter values
     * @throws LocalizedException
     */
    private function getSelectedValues($filter): array
    {
        $values = [];
        $state = $filter->getLayer()->getState();
        $requestVar = $filter->getRequestVar();

        foreach ($state->getFilters() as $stateFilter) {
            if ($stateFilter->getFilter()->getRequestVar() === $requestVar) {
                $values = (array)$stateFilter->getValue();
                break;
            }
        }

        return $values;
    }
}
