<?php
/**
 * @var $block \Smile\ElasticsuiteCatalog\Block\Navigation\Renderer\Category
 * @var $escaper \Magento\Framework\Escaper
 */

$filterCode = $block->getFilter()->getRequestVar(); // 'cat'
$datascope = $filterCode . 'Filter';
?>
<div data-bind="scope: '<?= $escaper->escapeHtmlAttr($datascope); ?>'">
    <!-- ko template: getTemplate() --> <!-- /ko -->
</div>
<script type="text/x-magento-init">
    {
        "*" : {
            "Magento_Ui/js/core/app": {
                "components": {
                    "<?= $escaper->escapeJs($datascope); ?>": {
                        "component": "Buhmann_Catalog/js/filter/category",
                        "template": "Buhmann_Catalog/layer/filter/category",
                        "filterCode": "<?= $escaper->escapeJs($filterCode); ?>",
                        "isMultipleSelectEnabled": <?= $block->isMultipleSelectEnabled() ? 'true' : 'false'; ?>
                    }
                }
            }
        }
    }
</script>
